// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Tp struct {
	ID           int32        `json:"id"`
	Titulo       string       `json:"titulo"`
	Materia      string       `json:"materia"`
	FechaEntrega time.Time    `json:"fecha_entrega"`
	Estado       string       `json:"estado"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
