// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const actualizarTP = `-- name: ActualizarTP :exec
UPDATE tps 
SET titulo = $1, materia = $2, fecha_entrega = $3, estado = $4 
WHERE id = $5
`

type ActualizarTPParams struct {
	Titulo       string    `json:"titulo"`
	Materia      string    `json:"materia"`
	FechaEntrega time.Time `json:"fecha_entrega"`
	Estado       string    `json:"estado"`
	ID           int32     `json:"id"`
}

func (q *Queries) ActualizarTP(ctx context.Context, arg ActualizarTPParams) error {
	_, err := q.db.ExecContext(ctx, actualizarTP,
		arg.Titulo,
		arg.Materia,
		arg.FechaEntrega,
		arg.Estado,
		arg.ID,
	)
	return err
}

const crearTP = `-- name: CrearTP :one
INSERT INTO tps (titulo, materia, fecha_entrega, estado)
VALUES ($1, $2, $3, $4)
RETURNING id, titulo, materia, fecha_entrega, estado, created_at
`

type CrearTPParams struct {
	Titulo       string    `json:"titulo"`
	Materia      string    `json:"materia"`
	FechaEntrega time.Time `json:"fecha_entrega"`
	Estado       string    `json:"estado"`
}

func (q *Queries) CrearTP(ctx context.Context, arg CrearTPParams) (Tp, error) {
	row := q.db.QueryRowContext(ctx, crearTP,
		arg.Titulo,
		arg.Materia,
		arg.FechaEntrega,
		arg.Estado,
	)
	var i Tp
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Materia,
		&i.FechaEntrega,
		&i.Estado,
		&i.CreatedAt,
	)
	return i, err
}

const eliminarTP = `-- name: EliminarTP :exec
DELETE FROM tps WHERE id = $1
`

func (q *Queries) EliminarTP(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, eliminarTP, id)
	return err
}

const listarTP = `-- name: ListarTP :many
SELECT id, titulo, materia, fecha_entrega, estado, created_at FROM tps ORDER BY fecha_entrega ASC
`

func (q *Queries) ListarTP(ctx context.Context) ([]Tp, error) {
	rows, err := q.db.QueryContext(ctx, listarTP)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tp
	for rows.Next() {
		var i Tp
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Materia,
			&i.FechaEntrega,
			&i.Estado,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerTP = `-- name: ObtenerTP :one
SELECT id, titulo, materia, fecha_entrega, estado, created_at FROM tps WHERE id = $1
`

func (q *Queries) ObtenerTP(ctx context.Context, id int32) (Tp, error) {
	row := q.db.QueryRowContext(ctx, obtenerTP, id)
	var i Tp
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Materia,
		&i.FechaEntrega,
		&i.Estado,
		&i.CreatedAt,
	)
	return i, err
}
